parameters:
  selected_transmits: focused # focused / plane
  zlims: [0.001, 0.039] # 38 mm
  xlims: [-0.019, 0.019] # 38 mm
  dynamic_range: [-60, 0]
  bandwidth: 7.0e+6

pipeline:
  operations:
    - band_pass_filter
    - apply_window
    - demodulate
    - name: downsample
      params:
        factor: 2
    - name: beamform
      params:
        beamformer: delay_and_sum
        enable_pfield: true
    - envelope_detect
    - normalize
    - log_compress
  jit_options: pipeline
