pipeline:
  operations:
    - name: demodulate
    - name: downsample
      params:
        factor: 1
    - name: beamform
      params:
        beamformer: delay_and_sum
        enable_pfield: false
    - name: envelope_detect
    - name: normalize
    - name: log_compress
